apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-jenkins-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sa-deployment-role
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "create", "update"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "patch", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-deployment
subjects:
- kind: ServiceAccount
  name: sa-jenkins-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: sa-deployment-role
  apiGroup: rbac.authorization.k8s.io
